In [15]:
precios

array([2.5 , 3.75, 4.5 , 5.  , 6.  , 6.  ])

In [14]:
#Eliminar un elemento de la lista
precios = np.delete(precios, 1)

In [12]:
#Agregar un elemento a la lista
precios = np.append(precios, 6)
precios

array([2.5 , 0.3 , 3.75, 4.5 , 5.  , 6.  , 6.  ])

In [10]:
#seleccionar un valor de la lista
precios[1]

np.float64(0.3)

In [8]:
precios + 3

array([5.5 , 3.3 , 6.75, 7.5 , 8.  ])

In [7]:
precios = np.array(precios)
precios

array([2.5 , 0.3 , 3.75, 4.5 , 5.  ])

In [5]:
precios = [2.5, 0.3, 3.75, 4.5, 5.0]
precios

[2.5, 0.3, 3.75, 4.5, 5.0]

In [1]:
import numpy as np